consultancy/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('accounts/',include('email_verify.urls')),
    path('', include('web_app.urls')),
    path('forms/wizard/',include('forms_service.wizard.urls'))
]

forms_service/wizard/urls.py
from . import views
from django.urls import path

app_name="forms_wizard"
urlpatterns = [
    path("definitions/", views.get_definitions,name="get_definitions"),
    path("definitions/<int:pk>", views.get_definition,name="get_definition"),
    path("fields/", views.get_all_fields,name="get_fields"),
    path("fields/<str:field_type>", views.get_field,name="get_field"),
]

web_app/urls.py
from django.urls import path
from . import views


app_name = 'web'
urlpatterns = [
    path('', views.home, name="home"),
    path('lang/<str:lang_code>/', views.set_lang,name="set_language"),
    path('accounts/profile',views.profile,name="profile"),
    path('dashboard/',views.dashboard,name="dashboard"),
    path('submissions/',views.submissions_index,name="submissions_index"),
    path('forms/wizard',views.wizard,name="wizard")
]

forms_service/wizard/views.py
from forms_service.models import FormDefinition
from forms_service.factories.field_factory import FieldFactory
from django.http import JsonResponse, Http404
from django.core.serializers.json import DjangoJSONEncoder
from django.shortcuts import get_object_or_404
from django.views.decorators.http import require_GET

## API ENDPOINTS FOR FORMS WIZARD ##
## TODO: @login_required for all
## TODO: @employee_required for static field and validator endpoints

@require_GET
## get all form definitions
def get_definitions(request):
    definitions = FormDefinition.objects.filter(status__in=['active', 'draft', 'pending_approval'])
    serialized_definitions = [{'name': d.name, 'status': d.status, 'description': d.description, 'version': d.version, 'definition': d.definition, 'translations':d.translations, 'default_lang_code': d.default_lang_code, 'created_at': str(d.created_at), 'created_by__name': d.created_by.name} for d in definitions]
    return JsonResponse(serialized_definitions, encoder=DjangoJSONEncoder, safe=False)

@require_GET
## get single form definition
def get_definition(request,pk):
    d = get_object_or_404(FormDefinition,pk=pk)
    serialized_definition = {'name': d.name, 'status': d.status, 'description': d.description, 'version': d.version, 'definition': d.definition, 'translations':d.translations, 'default_lang_code': d.default_lang_code, 'created_at': str(d.created_at), 'created_by__name': d.created_by.name}
    return JsonResponse(serialized_definition, encoder=DjangoJSONEncoder, safe=False)

@require_GET
## get all available fields
def get_all_fields(request):
    available = list(FieldFactory.FIELD_CLASSES.keys())
    return JsonResponse(available, encoder=DjangoJSONEncoder, safe=False)

@require_GET
## get details for a single field
def get_field(request,field_type):
    field = FieldFactory.FIELD_INFO.get(field_type.lower())
    if not field:
        return Http404()
    return JsonResponse(field,encoder=DjangoJSONEncoder,safe=False)

web_app/views.py
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.shortcuts import render,redirect
from django.urls import reverse

# Create your views here.

def home(req):
    return render(req,'home.html')

def set_lang(req, lang_code):
    req.session['django_language'] = lang_code
    return HttpResponseRedirect(req.GET.get('next',req.META.get('HTTP_REFERER', '/')))

@login_required
def profile(req):
    return render(req, 'accounts/settings.html')

@login_required
def dashboard(req):
    return redirect(reverse('web:home'))

@login_required
def submissions_index(req):
    return redirect(reverse('web:home'))

def wizard(req):
    return render(req,'wizard.html')

web_app/templates/base.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html lang="{% block langcode %}{{ request.session.django_language }}{% endblock langcode %}">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description"
              content='{% trans "This is a full-stack portfolio app, made for a consultancy agency that specializes in DV lottery visa consultancy. It showcases job-tracking, custom forms creation logic and customer and employee facing web application with full CRUD capabilities, email verification and multiple sign-up strategies" %}'>
        <meta name="keywords"
              content='{% trans "portfolio app, full-stack, crud, visa consultancy, diversity visa, live in us, diversity lottery" %}'>
        <title>
            {% if page_title %}
                {{ page_title }}
            {% else %}
                {% trans "Visa Consultancy Demo" %}
            {% endif %}
        </title>
        {% block head_includes %}
            <!-- Popperjs -->
            <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
                    crossorigin="anonymous"></script>
            <!-- Bootstrap CSS and JS -->
            <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
                  rel="stylesheet"
                  integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
                  crossorigin="anonymous" />
            <link rel="stylesheet"
                  href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
            <script defer
                    src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
                    integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
                    crossorigin="anonymous"></script>
        {% endblock head_includes %}
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        {% block head %}
        {% endblock head %}
    </head>
    <body>
        {% block header %}
            <header class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
                <a class="navbar-brand px-2 h1 m-1" href="{% url 'web:home' %}">{% trans "VISA CONSULTANCY" %}</a>
                <button class="navbar-toggler"
                        type="button"
                        data-bs-toggle="collapse"
                        data-bs-target="#navbarNav"
                        aria-controls="navbarNav"
                        aria-expanded="false"
                        aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse mx-2" id="navbarNav">
                    <ul class="navbar-nav navbar-nav-dark ms-auto">
                        <li class="nav-item">
                            {% url 'web:home' as link %}
                            <a class="nav-link {% if request.get_full_path == link %}active{% endif %}"
                               href="{% url 'web:home' %}">{% trans "Home" %}</a>
                        </li>
                        {% if user.is_authenticated and user.profile.role == 'employee' %}
                            <li class="nav-item">
                                {% url 'web:dashboard' as link %}
                                <a class="nav-link {% if request.get_full_path == link %}active{% endif %}"
                                   href="{% url 'web:dashboard' %}">{% trans "Dashboard" %}</a>
                            </li>
                            <li class="nav-item">
                                {% url 'web:wizard' as link %}
                                <a class="nav-link {% if request.get_full_path == link %}active{% endif %}"
                                   href="{% url 'web:wizard' %}">{% trans "Forms Wizard" %}</a>
                            </li>
                        {% elif user.is_authenticated and user.profile.role == 'customer' %}
                            <li class="nav-item">
                                {% url 'web:submissions_index' as link %}
                                <a class="nav-link {% if request.get_full_path == link %}active{% endif %}"
                                   href="{% url 'web:submissions_index' %}">{% trans "My Submissions" %}</a>
                            </li>
                        {% endif %}
                        <li class="nav-item dropdown d-flex">
                            <a class="nav-link dropdown-toggle align-middle"
                               href="#"
                               id="accountDropdown"
                               role="button"
                               data-bs-toggle="dropdown"
                               aria-expanded="false"><i class="bi bi-person-circle text-white align-middle m-2"></i></a>
                            <ul class="dropdown-menu dropdown-menu-dark dropdown-menu-end"
                                aria-labelledby="accountDropdown">
                                {% if not user.is_authenticated %}
                                    <li>
                                        <div class="card bg-dark text-white">
                                            <div class="card-body">
                                                <form method="post" action="{% url 'account_login' %}">
                                                    {% csrf_token %}
                                                    <div>
                                                        <label for="login">{% trans "Email" %}:</label>
                                                        <input autocomplete="email"
                                                               class="form-control form-control-sm"
                                                               type="email"
                                                               name="login">
                                                    </div>
                                                    <div>
                                                        <label for="password">{% trans "Password" %}:</label>
                                                        <input autocomplete="current-password"
                                                               class="form-control form-control-sm"
                                                               type="password"
                                                               name="password">
                                                    </div>
                                                    <div class="d-flex justify-content-between">
                                                        <input class="btn btn-flat text-white"
                                                               type="submit"
                                                               value='{% trans "Login" %}'>
                                                        <a class="btn btn-flat text-white align-middle"
                                                           href="{% url 'account_signup' %}">{% trans "Signup" %}</a>
                                                    </div>
                                                </form>
                                                <form method="post" action="{% url 'google_login' %}">
                                                    {% csrf_token %}
                                                    <div class="row d-flex justify-content-middle">
                                                        <button class="btn btn-sm btn-outline-secondary mx-auto flex-fill"
                                                                type="submit">
                                                            <img width=""
                                                                 height=""
                                                                 src="{% static 'images/google_logo.svg' %}"
                                                                 alt="google logo">
                                                            {% trans "Google Sign-in" %}
                                                        </button>
                                                    </div>
                                                </form>
                                            </div>
                                        </div>
                                    </li>
                                {% else %}
                                    <li class="nav-item d-flex flex-column align-content-stretch">
                                        {% url 'web:profile' as link %}
                                        <a class="nav-link btn btn-flat {% if request.get_full_path == link %}active{% endif %}"
                                           href="{% url 'web:profile' %}">{% trans "Account Settings" %}</a>
                                    </li>
                                    <form method="post" action="{% url 'account_logout' %}">
                                        {% csrf_token %}
                                        <li class="nav-item d-flex flex-column align-content-stretch">
                                            <input class="nav-link btn btn-flat"
                                                   type="submit"
                                                   value="{% trans "Logout" %}">
                                        </li>
                                    </form>
                                {% endif %}
                            </ul>
                        </li>
                        <li class="nav-item dropdown ">
                            <a class="nav-link dropdown-toggle"
                               href="#"
                               id="languageDropdown"
                               role="button"
                               data-bs-toggle="dropdown"
                               aria-expanded="false">
                                {% comment %} {% trans "Language" %}: {% endcomment %}
                                {% get_current_language as LANGUAGE_CODE %}
                                {% get_language_info for LANGUAGE_CODE as lang %}
                                {% for code, flag in FLAGS %}
                                    {% if code|lower == LANGUAGE_CODE %}{{ flag }} {{ lang.code|upper }}{% endif %}
                                {% endfor %}
                            </a>
                            <ul class="dropdown-menu dropdown-menu-dark dropdown-menu-end"
                                aria-labelledby="languageDropdown">
                                {% for code, name in LANGUAGES %}
                                    <li>
                                        <a class="dropdown-item {% if code|lower == LANGUAGE_CODE %}active{% endif %}"
                                           href="{% url 'web:set_language' code %}?next={{ request.get_full_path|urlencode }}">
                                            {% for flag_code, flag in FLAGS %}
                                                {% if flag_code == code %}{{ flag }}{% endif %}
                                            {% endfor %}
                                            {{ name }}
                                        </a>
                                    </li>
                                {% endfor %}
                            </ul>
                        </li>
                    </ul>
                </div>
            </header>
        {% endblock header %}
        <main class="{% block main_class %}mt-0{% endblock main_class %}">
        {% block content %}
        {% endblock content %}
        </main>
        <footer class="{% block footer_class %}bg-dark text-white bottom-0 w-100 d-flex p-2 justify-content-center{% endblock footer_class %}">
            {% block footer %}
            can@göloğlu.com, © 2023
            {% endblock footer %}
        </footer>
    </body>
</html>

web_app/templates/home.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block head %}
    <script src="{% static 'js/frontend.js' %}"></script>
{% endblock head %}
{% block content %}
    <div class="parallax-container">
        <div class="parallax">
            {% comment %} {% if not user.is_authenticated %}
                <div class="parallax-text-container">
                    <div class="parallax-text shadow text-center">
                        {% trans "You too can live in U.S.A!" %}
                        <br>
                        <div class="text-center">{% trans "Scroll to find out how" %} ⬇</div>
                    </div>
                </div>
            {% endif %} {% endcomment %}
            <img height=""
                 width=""
                 src="{% static 'images/lady_liberty.webp' %}"
                 alt="{% trans "ink on paper sketch of Lady Liberty on a wooden surface" %}">
        </div>
    </div>
    <div class="container-sm">
        <p>
            Lorem, ipsum dolor sit amet consectetur adipisicing elit. Illum repellat asperiores vero laudantium dignissimos velit aliquid quidem labore eligendi ullam eum itaque cum nesciunt quibusdam maiores cupiditate, veritatis fugit error!
        </p>
        <p>
            Lorem, ipsum dolor sit amet consectetur adipisicing elit. Illum repellat asperiores vero laudantium dignissimos velit aliquid quidem labore eligendi ullam eum itaque cum nesciunt quibusdam maiores cupiditate, veritatis fugit error!
        </p>
        <p>
            Lorem, ipsum dolor sit amet consectetur adipisicing elit. Illum repellat asperiores vero laudantium dignissimos velit aliquid quidem labore eligendi ullam eum itaque cum nesciunt quibusdam maiores cupiditate, veritatis fugit error!
        </p>
        <p>
            Lorem, ipsum dolor sit amet consectetur adipisicing elit. Illum repellat asperiores vero laudantium dignissimos velit aliquid quidem labore eligendi ullam eum itaque cum nesciunt quibusdam maiores cupiditate, veritatis fugit error!
        </p>
        <p>
            Lorem, ipsum dolor sit amet consectetur adipisicing elit. Illum repellat asperiores vero laudantium dignissimos velit aliquid quidem labore eligendi ullam eum itaque cum nesciunt quibusdam maiores cupiditate, veritatis fugit error!
        </p>
        <p>
            Lorem, ipsum dolor sit amet consectetur adipisicing elit. Illum repellat asperiores vero laudantium dignissimos velit aliquid quidem labore eligendi ullam eum itaque cum nesciunt quibusdam maiores cupiditate, veritatis fugit error!
        </p>
        <p>
            Lorem, ipsum dolor sit amet consectetur adipisicing elit. Illum repellat asperiores vero laudantium dignissimos velit aliquid quidem labore eligendi ullam eum itaque cum nesciunt quibusdam maiores cupiditate, veritatis fugit error!
        </p>
        <p>
            Lorem, ipsum dolor sit amet consectetur adipisicing elit. Illum repellat asperiores vero laudantium dignissimos velit aliquid quidem labore eligendi ullam eum itaque cum nesciunt quibusdam maiores cupiditate, veritatis fugit error!
        </p>
        <p>
            Lorem, ipsum dolor sit amet consectetur adipisicing elit. Illum repellat asperiores vero laudantium dignissimos velit aliquid quidem labore eligendi ullam eum itaque cum nesciunt quibusdam maiores cupiditate, veritatis fugit error!
        </p>
        <p>
            Lorem, ipsum dolor sit amet consectetur adipisicing elit. Illum repellat asperiores vero laudantium dignissimos velit aliquid quidem labore eligendi ullam eum itaque cum nesciunt quibusdam maiores cupiditate, veritatis fugit error!
        </p>
        <p>
            Lorem, ipsum dolor sit amet consectetur adipisicing elit. Illum repellat asperiores vero laudantium dignissimos velit aliquid quidem labore eligendi ullam eum itaque cum nesciunt quibusdam maiores cupiditate, veritatis fugit error!
        </p>
        <p>
            Lorem, ipsum dolor sit amet consectetur adipisicing elit. Illum repellat asperiores vero laudantium dignissimos velit aliquid quidem labore eligendi ullam eum itaque cum nesciunt quibusdam maiores cupiditate, veritatis fugit error!
        </p>
        <p>
            Lorem, ipsum dolor sit amet consectetur adipisicing elit. Illum repellat asperiores vero laudantium dignissimos velit aliquid quidem labore eligendi ullam eum itaque cum nesciunt quibusdam maiores cupiditate, veritatis fugit error!
        </p>
        <p>
            Lorem, ipsum dolor sit amet consectetur adipisicing elit. Illum repellat asperiores vero laudantium dignissimos velit aliquid quidem labore eligendi ullam eum itaque cum nesciunt quibusdam maiores cupiditate, veritatis fugit error!
        </p>
        <p>
            Lorem, ipsum dolor sit amet consectetur adipisicing elit. Illum repellat asperiores vero laudantium dignissimos velit aliquid quidem labore eligendi ullam eum itaque cum nesciunt quibusdam maiores cupiditate, veritatis fugit error!
        </p>
        <p>
            Lorem, ipsum dolor sit amet consectetur adipisicing elit. Illum repellat asperiores vero laudantium dignissimos velit aliquid quidem labore eligendi ullam eum itaque cum nesciunt quibusdam maiores cupiditate, veritatis fugit error!
        </p>
        <p>
            Lorem, ipsum dolor sit amet consectetur adipisicing elit. Illum repellat asperiores vero laudantium dignissimos velit aliquid quidem labore eligendi ullam eum itaque cum nesciunt quibusdam maiores cupiditate, veritatis fugit error!
        </p>
        <p>
            Lorem, ipsum dolor sit amet consectetur adipisicing elit. Illum repellat asperiores vero laudantium dignissimos velit aliquid quidem labore eligendi ullam eum itaque cum nesciunt quibusdam maiores cupiditate, veritatis fugit error!
        </p>
    </div>
    <div class="parallax"></div>
    <script>
    parallaxElements = document.querySelectorAll('.parallax');
    F.Parallax.init(parallaxElements, {minHeight: '100vh'});
    </script>
{% endblock content %}

web_app/templates/wizard.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block head_includes %}
<!-- Popperjs -->
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
crossorigin="anonymous"></script>
<!-- Bootstrap CSS and JS -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
rel="stylesheet"
integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
crossorigin="anonymous" />
<link rel="stylesheet"
href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
<script defer
src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
crossorigin="anonymous"></script>
<script defer src="{% static 'js/main.2edeb902.js' %}"></script>
<link rel="stylesheet" href="{% static 'css/main.69c12962.css' %}">
{% endblock head_includes %}
{% block content %}
<div id="react-root">
</div>
{% endblock content %}